version: 2.0

jobs:
  verify:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: target/site/serenity

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn clean install -Dmaven.test.skip=true

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - verify:
          requires:
            - build
